[package]
name = "halberd"
version = "0.2.0"
edition = "2018"
authors = [
	"o108minmin <o108minmin@gmail.com>",
]
description = "Generate Software Talk Subtitle"
repository = "https://github.com/o108minmin/halberd"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "*"
hound = "*"
chrono = "*"
clap = "3.0.0-beta.4"
