on: [push]

name: Lint

jobs:
  check:
    name: Run cargo check clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - run: cargo clippy --workspace --exclude halberd_gui
